"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
const LABEL:any={ENTRADA:"Entrada",INTERVALO_INICIO:"Início do intervalo",INTERVALO_FIM:"Fim do intervalo",SAIDA:"Saída"};
const fmt=(n:number|null|undefined,s=false)=>{if(n==null)return"—";const sign=n<0?"-":s&&n>0?"+":"";const a=Math.abs(n);return`${sign}${String(Math.floor(a/60)).padStart(2,"0")}h${String(a%60).padStart(2,"0")}`};
export default function Ponto(){const router=useRouter();const [data,setData]=useState<any>(null);const [error,setError]=useState("");const [clock,setClock]=useState("00:00:00");const timer=useRef<any>(null);const csrf=()=>sessionStorage.getItem("cvt_csrf")||"";
 const api=useCallback(async(url:string,opt:RequestInit={})=>{const h=new Headers(opt.headers);if(opt.body)h.set("content-type","application/json");if(opt.method&&opt.method!=="GET")h.set("x-csrf-token",csrf());const r=await fetch(url,{...opt,headers:h});if(r.status===401){router.replace("/");throw new Error("Sessão expirada");}const d=await r.json();if(!r.ok)throw new Error(d.error||"Erro");return d;},[router]);
 const load=useCallback(async()=>{try{const d=await api("/api/employee/dashboard");setData(d);const start=new Date(d.server_time).getTime(),local=Date.now();if(timer.current)clearInterval(timer.current);const tick=()=>setClock(new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(start+(Date.now()-local))));tick();timer.current=setInterval(tick,1000);}catch(e){setError(e instanceof Error?e.message:"Erro");}},[api]);useEffect(()=>{void load();return()=>{if(timer.current)clearInterval(timer.current)}},[load]);
 async function punch(){try{await api("/api/employee/punch",{method:"POST",body:"{}"});await load();}catch(e){setError(e instanceof Error?e.message:"Erro");}}
 async function logout(){await api("/api/auth/logout",{method:"POST",body:"{}"});sessionStorage.removeItem("cvt_csrf");router.replace("/");}
 return <main className="employeePage"><header className="employeeHeader"><div><p className="eyebrow">REGISTRO DE PONTO</p><h1>{data?.employee.name??"Funcionário"}</h1></div><button className="secondary" onClick={logout}>Sair</button></header><section className="clockPanel"><p className="dateLine">Hora oficial do servidor</p><div className="liveClock">{clock}</div><p className="serverNote">America/Sao_Paulo</p><div className="nextPunch">{data?.next_type?`Próxima batida: ${LABEL[data.next_type]}`:"Jornada do dia concluída."}</div><button className="punchButton" onClick={punch} disabled={!data?.next_type}>{data?.next_type?`REGISTRAR ${LABEL[data.next_type].toUpperCase()}`:"JORNADA CONCLUÍDA"}</button>{error&&<div className="alert error" onClick={()=>setError("")}>{error}</div>}</section><section className="employeeMetrics">{[["Horas trabalhadas",fmt(data?.totals.worked_minutes)],["Horas positivas",fmt(data?.totals.positive_minutes)],["Horas negativas",fmt(data?.totals.negative_minutes)],["Saldo",fmt(data?.totals.balance_minutes,true)]].map(([l,v])=><article className="metric" key={l}><span>{l}</span><strong>{v}</strong></article>)}</section><section className="panel"><div className="sectionHead"><div><p className="eyebrow">HOJE</p><h2>{data?.today.status??"SEM REGISTRO"}</h2></div></div><div className="punchGrid">{[["Entrada",data?.today.entrada],["Início intervalo",data?.today.intervalo_inicio],["Fim intervalo",data?.today.intervalo_fim],["Saída",data?.today.saida]].map(([l,v])=><div key={l}><span>{l}</span><strong>{v?String(v).slice(0,5):"—"}</strong></div>)}</div></section><section className="panel tableWrap"><h2>Últimos registros</h2><table><thead><tr><th>Data</th><th>Trabalhado</th><th>Saldo</th><th>Status</th></tr></thead><tbody>{data?.recent?.map((r:any)=><tr key={r.date}><td>{r.date}</td><td>{fmt(r.worked_minutes)}</td><td>{fmt(r.balance_minutes,true)}</td><td>{r.status}</td></tr>)}</tbody></table></section></main>}
