"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
type Emp={id:number;name:string;cpf:string;admission_date:string;status:"ATIVO"|"INATIVO";login:string};
type Totals={worked_minutes:number;positive_minutes:number;negative_minutes:number;balance_minutes:number;pending:number};
type Dash={total:number;active:number;inactive:number;totals:Totals;employees:Array<{id:number;name:string;login:string;status:string;totals:Totals;today_status:string}>};
type Report={month:string;employee_label:string;totals:Totals;rows:Array<any>};
const fmt=(n:number|null|undefined,s=false)=>{if(n==null)return"—";const sign=n<0?"-":s&&n>0?"+":"";const a=Math.abs(n);return`${sign}${String(Math.floor(a/60)).padStart(2,"0")}h${String(a%60).padStart(2,"0")}`};
export default function Admin(){ const router=useRouter(); const [view,setView]=useState<"dashboard"|"employees"|"report">("dashboard"); const [dash,setDash]=useState<Dash|null>(null); const [employees,setEmployees]=useState<Emp[]>([]); const [error,setError]=useState(""); const [report,setReport]=useState<Report|null>(null); const [reportEmp,setReportEmp]=useState("ALL"); const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)); const [notice,setNotice]=useState(""); const [passwordEmp,setPasswordEmp]=useState<Emp|null>(null); const [newPassword,setNewPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState("");
  const csrf=()=>sessionStorage.getItem("cvt_csrf")||"";
  const api=useCallback(async(url:string,opt:RequestInit={})=>{const h=new Headers(opt.headers); if(opt.body)h.set("content-type","application/json"); if(opt.method&&opt.method!=="GET")h.set("x-csrf-token",csrf()); const r=await fetch(url,{...opt,headers:h}); if(r.status===401){router.replace("/");throw new Error("Sessão expirada.");} const d=await r.json(); if(!r.ok)throw new Error(d.error||"Erro"); return d;},[router]);
  const load=useCallback(async()=>{setError("");const [d,e]=await Promise.allSettled([api("/api/admin/dashboard"),api("/api/admin/employees")]);if(d.status==="fulfilled")setDash(d.value);if(e.status==="fulfilled")setEmployees(e.value.employees);const errors=[d,e].filter((x):x is PromiseRejectedResult=>x.status==="rejected").map(x=>x.reason instanceof Error?x.reason.message:"Erro ao carregar dados.");if(errors.length)setError(errors.join(" • "));},[api]); useEffect(()=>{void load()},[load]);
  async function logout(){await api("/api/auth/logout",{method:"POST",body:"{}"});sessionStorage.removeItem("cvt_csrf");router.replace("/");}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);try{await api("/api/admin/employees",{method:"POST",body:JSON.stringify({name:f.get("name"),cpf:f.get("cpf"),admission_date:f.get("admission"),status:f.get("status"),login:f.get("login"),password:f.get("password")})});e.currentTarget.reset();setView("employees");await load();}catch(e){setError(e instanceof Error?e.message:"Erro");}}
  async function toggle(emp:Emp){try{setNotice("");await api(`/api/admin/employees/${emp.id}/status`,{method:"PATCH",body:JSON.stringify({status:emp.status==="ATIVO"?"INATIVO":"ATIVO"})});await load();}catch(e){setError(e instanceof Error?e.message:"Erro");}}\n  async function resetPassword(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!passwordEmp)return;setError("");setNotice("");if(newPassword.length<8||newPassword.length>128){setError("A senha precisa ter entre 8 e 128 caracteres.");return}if(newPassword!==confirmPassword){setError("As senhas não conferem.");return}try{await api(`/api/admin/employees/${passwordEmp.id}/password`,{method:"PATCH",body:JSON.stringify({password:newPassword})});setNotice(`Senha de ${passwordEmp.name} redefinida com sucesso.`);setPasswordEmp(null);setNewPassword("");setConfirmPassword("");}catch(e){setError(e instanceof Error?e.message:"Erro ao redefinir senha.");}}
  async function generate(){try{setReport(await api(`/api/admin/report?employeeId=${encodeURIComponent(reportEmp)}&month=${encodeURIComponent(month)}`));}catch(e){setError(e instanceof Error?e.message:"Erro");}}
  function exportCsv(){if(!report)return;const safe=(v:any)=>{let t=String(v??"");if(/^[=+\-@]/.test(t))t="'"+t;return`"${t.replaceAll('"','""')}"`};const lines=[["Funcionário","Data","Entrada","Início intervalo","Fim intervalo","Saída","Trabalhado","Previsto","Positivas","Negativas","Saldo","Status"].map(safe).join(";")];for(const r of report.rows)lines.push([r.employee_name,r.date,r.entrada,r.intervalo_inicio,r.intervalo_fim,r.saida,fmt(r.worked_minutes),fmt(r.expected_minutes),r.balance_minutes>0?fmt(r.balance_minutes,true):"00h00",r.balance_minutes<0?"-"+fmt(Math.abs(r.balance_minutes)):"00h00",fmt(r.balance_minutes,true),r.status].map(safe).join(";"));const b=new Blob(["\ufeff"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=`relatorio-cvt-${month}.csv`;a.click();URL.revokeObjectURL(u);}
  return <div className="appShell"><aside className="sidebar"><div className="sideBrand"><div className="brandMark small">CVT</div><div><strong>Controle de Ponto</strong><small>Área administrativa</small></div></div><nav>{[["dashboard","Dashboard"],["employees","Funcionários"],["report","Relatório mensal"]].map(([k,l])=><button key={k} className={view===k?"active":""} onClick={()=>setView(k as any)}>{l}</button>)}</nav><button className="logout" onClick={logout}>Sair</button></aside><main className="content"><header className="topbar"><div><p className="eyebrow">CVT</p><h1>Painel Administrativo</h1></div><span className="secureBadge">Sessão protegida</span></header>{error&&<div className="alert error" onClick={()=>setError("")}>{error}</div>}{notice&&<div className="alert" onClick={()=>setNotice("")}>{notice}</div>}
  {view==="dashboard"&&<><div className="metrics">{[["Funcionários",dash?.total??0],["Ativos",dash?.active??0],["Horas trabalhadas",fmt(dash?.totals.worked_minutes)],["Horas positivas",fmt(dash?.totals.positive_minutes)],["Horas negativas",fmt(dash?.totals.negative_minutes)],["Saldo",fmt(dash?.totals.balance_minutes,true)]].map(([l,v])=><article className="metric" key={l}><span>{l}</span><strong>{v}</strong></article>)}</div><div className="panel tableWrap"><table><thead><tr><th>Funcionário</th><th>Usuário</th><th>Trabalhado</th><th>Positivas</th><th>Negativas</th><th>Saldo</th><th>Status hoje</th></tr></thead><tbody>{dash?.employees.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.login}</td><td>{fmt(e.totals.worked_minutes)}</td><td>{fmt(e.totals.positive_minutes)}</td><td>{fmt(e.totals.negative_minutes)}</td><td>{fmt(e.totals.balance_minutes,true)}</td><td>{e.today_status}</td></tr>)}</tbody></table></div></>}
  {view==="employees"&&<><div className="panel"><div className="sectionHead"><div><p className="eyebrow">CADASTRO</p><h2>Novo funcionário</h2></div><span className="badge">{employees.length}/3</span></div><form className="formGrid" onSubmit={create}><label>Nome<input name="name" required /></label><label>CPF<input name="cpf" required /></label><label>Data de admissão<input name="admission" type="date" required /></label><label>Status<select name="status"><option>ATIVO</option><option>INATIVO</option></select></label><label>Usuário<input name="login" minLength={3} maxLength={40} required /></label><label>Senha<input name="password" type="password" minLength={8} maxLength={128} required /></label><div className="formAction"><button className="primary">CADASTRAR FUNCIONÁRIO</button></div></form></div><div className="panel tableWrap"><table><thead><tr><th>Nome</th><th>Usuário</th><th>CPF</th><th>Admissão</th><th>Status</th><th>Ações</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.login}</td><td>{e.cpf}</td><td>{e.admission_date}</td><td>{e.status}</td><td><div className="reportActions"><button className="secondary" onClick={()=>toggle(e)}>{e.status==="ATIVO"?"Inativar":"Ativar"}</button><button className="dark" onClick={()=>{setPasswordEmp(e);setNewPassword("");setConfirmPassword("");setError("");setNotice("");}}>Redefinir senha</button></div></td></tr>)}</tbody></table></div>{passwordEmp&&<div className="panel"><div className="sectionHead"><div><p className="eyebrow">SEGURANÇA</p><h2>Redefinir senha — {passwordEmp.name}</h2></div><button className="secondary" type="button" onClick={()=>setPasswordEmp(null)}>Cancelar</button></div><form className="formGrid" onSubmit={resetPassword}><label>Nova senha<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={8} maxLength={128} autoComplete="new-password" required /></label><label>Confirmar senha<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={8} maxLength={128} autoComplete="new-password" required /></label><div className="formAction"><button className="primary">SALVAR NOVA SENHA</button></div></form><p className="eyebrow">A senha permanecerá válida até uma nova redefinição. As sessões antigas do funcionário serão encerradas.</p></div>}</>}
  {view==="report"&&<><div className="panel noPrint"><p className="eyebrow">FECHAMENTO</p><h2>Relatório mensal</h2><div className="reportTools"><label>Funcionário<select value={reportEmp} onChange={e=>setReportEmp(e.target.value)}><option value="ALL">Todos os funcionários</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Mês<input type="month" value={month} onChange={e=>setMonth(e.target.value)} /></label><div className="reportActions"><button className="primary" onClick={generate}>GERAR</button><button className="secondary" onClick={exportCsv} disabled={!report}>EXCEL / CSV</button><button className="dark" onClick={()=>window.print()} disabled={!report}>IMPRIMIR / PDF</button></div></div></div><div className="panel printArea"><div className="reportHeader"><div><p className="eyebrow">RELATÓRIO MENSAL DE HORAS</p><h2>{report?.month??"Selecione um período"}</h2><span>{report?.employee_label??""}</span></div><strong>Corrente da Vida Treinamentos — CVT</strong></div><div className="reportSummary">{[["Trabalhadas",fmt(report?.totals.worked_minutes)],["Positivas",fmt(report?.totals.positive_minutes)],["Negativas",fmt(report?.totals.negative_minutes)],["Saldo",fmt(report?.totals.balance_minutes,true)],["Pendências",report?.totals.pending??0]].map(([l,v])=><article className="metric" key={l}><span>{l}</span><strong>{v}</strong></article>)}</div><div className="tableWrap"><table><thead><tr><th>Funcionário</th><th>Data</th><th>Entrada</th><th>Início intervalo</th><th>Fim intervalo</th><th>Saída</th><th>Trabalhado</th><th>Previsto</th><th>Saldo</th><th>Status</th></tr></thead><tbody>{report?.rows.map((r,i)=><tr key={i}><td>{r.employee_name}</td><td>{r.date}</td><td>{r.entrada??"—"}</td><td>{r.intervalo_inicio??"—"}</td><td>{r.intervalo_fim??"—"}</td><td>{r.saida??"—"}</td><td>{fmt(r.worked_minutes)}</td><td>{fmt(r.expected_minutes)}</td><td>{fmt(r.balance_minutes,true)}</td><td>{r.status}</td></tr>)}</tbody></table></div></div></>}
  </main></div> }
